[
  {
    "id": 1,
    "title": "Default Department",
    "iconName": "icon-default",
    "emotion": "excitement",
    "logo": true,
    "color": "black",
    "Layers": [
      {
        "id": 0,
        "layer": "image",
        "x": 0,
        "y": 0,
        "width": "100%",
        "height": "100%",
        "aspectRatio": 1,
        "objectFit": "contain",
        "imageUrl": "https://images.unsplash.com/photo-1719937050445-098888c0625e?q=80&w=1374&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
        "mask": "url(#fade-mask)",
        "maskId": "fade-bottom",
        "maskFilter": "url(#fade-bottom)",
        "filter": "url(#f)",
        "display": "block",
        "rotate": 0,
        "transform": "rotate(0deg)",
        "dx": "0",
        "dy": "0"
      },
      {
        "id": 1,
        "layer": "circle",
        "x": 200,
        "y": 200,
        "radius": 100,
        "fill": "none",
        "strokeOpacity": 1,
        "fillOpacity": 1,
        "opacity": 1,
        "stroke": "green",
        "strokeWidth": 50,
        "strokeLinecap": "round",
        "strokeLinejoin": "round",
        "paintOrder": "stroke",
        "strokeMiterlimit": 10,
        "strokeDasharray": 1000,
        "clipPath": "none",
        "display": "block",
        "rotate": 45,
        "transform": "rotate(45deg)",
        "dx": "10",
        "dy": "10"
      },
      {
        "id": 2,
        "layer": "rect",
        "x": 300,
        "y": 300,
        "width": "150%",
        "height": "90%",
        "fill": "url(#grad)",
        "filter": "url(#crumple-effect)",
        "stroke": "url(#img1)",
        "strokeWidth": 25,
        "rx": 10,
        "ry": 0,
        "display": "none",
        "rotate": 30,
        "transform": "rotate(30deg)",
        "dx": "-20",
        "dy": "-20"
      },
      {
        "id": 3,
        "layer": "rect",
        "x": 300,
        "y": 300,
        "width": "100%",
        "height": "100%",
        "strokeWidth": 25,
        "fill": "url(#grid)",
        "rx": 0,
        "ry": 0,
        "opacity": "0.6",
        "display": "none",
        "rotate": 60,
        "transform": "rotate(60deg)",
        "dx": "15",
        "dy": "25"
      },
      {
        "id": 4,
        "layer": "rect",
        "x": 300,
        "y": 300,
        "width": "100%",
        "height": "100%",
        "strokeWidth": 25,
        "fill": "url(#dots)",
        "rx": 0,
        "ry": 0,
        "opacity": "0.6",
        "display": "none",
        "rotate": 60,
        "transform": "rotate(60deg)",
        "dx": "15",
        "dy": "25"
      },
      {
        "id": 5,
        "layer": "text",
        "x": "100",
        "y": "200",
        "fill": "white",
        "fontFamily": "Gloss_And_Bloom",
        "fontSize": "10em",
        "fontWeight": "bold",
        "fontStyle": "normal",
        "lineHeight": 1.5,
        "letterSpacing": 0,
        "textTransform": "uppercase",
        "textShadow": "none",
        "dominantBaseline": "middle",
        "content": "Peace Nangoli",
        "opacity": 1,
        "filter": "none",
        "display": "",
        "className": "ico",
        "rotate": 90,
        "transform": "none",
        "dx": "10",
        "dy": "20"
      },
      {
        "id": 6,
        "layer": "image",
        "x": 10,
        "y": 10,
        "width": "100%",
        "height": "100%",
        "aspectRatio": 5,
        "objectFit": "contain",
        "imageUrl": "none",
        "display": "none",
        "rotate": 0,
        "transform": "rotate(0deg)",
        "dx": "0",
        "dy": "0"
      },
      {
        "id": 7,
        "layer": "line",
        "x": 100,
        "y": 200,
        "x1": 34.4,
        "y1": 37.9,
        "x2": 95.8,
        "y2": 92.3,
        "stroke": "none",
        "strokeWidth": 10,
        "display": "none",
        "rotate": 15,
        "transform": "rotate(15deg)",
        "dx": "0",
        "dy": "0"
      },
      {
        "id": 8,
        "layer": "line",
        "x": 100,
        "y": 200,
        "x1": 95.8,
        "y1": 38,
        "x2": 34.4,
        "y2": 92.2,
        "stroke": "none",
        "strokeWidth": 10,
        "display": "none",
        "rotate": -15,
        "transform": "rotate(-15deg)",
        "dx": "0",
        "dy": "0"
      },
      {
        "id": 9,
        "layer": "",
        "x": 200,
        "y": 200,
        "points": "",
        "stroke": "green",
        "strokeWidth": 10,
        "fill": "",
        "sx": " ",
        "display": "none",
        "rotate": 45,
        "transform": "rotate(45deg)",
        "dx": "10",
        "dy": "5"
      },
      {
        "id": 10,
        "layer": "g",
        "x": 200,
        "y": 200,
        "pointData": "<g fill=\"none\"><circle id=\"circle\" stroke=\"#73AF55\" strokeWidth=\"15\" cx=\"65.1\" cy=\"65.1\" r=\"70\" /><polyline id=\"check\" stroke=\"#73AF55\" strokeWidth=\"15\" strokeLinecap=\"round\" points=\"100.2,40.2 51.5,88.8 29.8,67.5\" /></g>",
        "sx": "polylineStyleGreen",
        "display": "block",
        "rotate": 90,
        "transform": "rotate(90deg)",
        "dx": "-10",
        "dy": "10"
      },
      {
        "id": 11,
        "layer": "use",
        "x": 20,
        "y": 200,
        "width": "100px",
        "height": "100px",
        "pointData": "",
        "sx": "none",
        "display": "none",
        "rotate": 0,
        "transform": "rotate(0deg)",
        "dx": "5",
        "dy": "-5"
      },
      {
        "id": 12,
        "layer": "path",
        "x": 20,
        "y": 200,
        "width": "100px",
        "height": "100px",
        "d": "none",
        "fill": "#fff",
        "opacity": "1",
        "strokelinecap": "round",
        "strokeLinejoin": "round",
        "stroke": "black",
        "strokeWidth": "1",
        "strokeLinejoin": "round",
        "strokeLinecap": "round",
        "strokeOpacity": "",
        "fillOpacity": "1",
        "sx": "none",
        "display": "none",
        "rotate": 135,
        "transform": "rotate(135deg)",
        "dx": "0",
        "dy": "0"
      },
      {
        "id": 13,
        "circleId": "c4",
        "layer": "foreignObject",
        "x": 300,
        "y": 300,
        "width": "100%",
        "height": "100%",
        "display": "none"
      }
    ]
  },
  {
    "id": 2,
    "title": "Default Department",
    "iconName": "icon-default",
    "emotion": "excitement",
    "logo": true,
    "color": "brown",
    "Layers": [
      {
        "id": 0,
        "layer": "image",
        "x": 0,
        "y": 0,
        "width": "100%",
        "height": "100%",
        "aspectRatio": 1,
        "objectFit": "contain",
        "imageUrl": "none",
        "maskId": "none",
        "maskFilter": "none",
        "filter": "saturate(50%) url(#anaglyph3d) url(#f)",
        "display": "block",
        "rotate": 0,
        "transform": "rotate(0deg)",
        "dx": "0",
        "dy": "0"
      },
      {
        "id": 1,
        "layer": "circle",
        "x": 200,
        "y": 200,
        "radius": 100,
        "fill": "none",
        "strokeOpacity": 1,
        "fillOpacity": 1,
        "opacity": 1,
        "stroke": "green",
        "strokeWidth": 50,
        "strokeLinecap": "round",
        "strokeLinejoin": "round",
        "paintOrder": "stroke",
        "strokeMiterlimit": 10,
        "strokeDasharray": 1000,
        "clipPath": "none",
        "display": "block",
        "rotate": 45,
        "transform": "rotate(45deg)",
        "dx": "10",
        "dy": "10"
      },
      {
        "id": 2,
        "layer": "rect",
        "x": 300,
        "y": 300,
        "width": "150%",
        "height": "90%",
        "fill": "url(#grad)",
        "filter": "url(#crumple-effect)",
        "stroke": "url(#img1)",
        "strokeWidth": 25,
        "rx": 10,
        "ry": 0,
        "display": "none",
        "rotate": 30,
        "transform": "rotate(30deg)",
        "dx": "-20",
        "dy": "-20"
      },
      {
        "id": 3,
        "layer": "rect",
        "x": 300,
        "y": 300,
        "width": "100%",
        "height": "100%",
        "strokeWidth": 25,
        "fill": "url(#grid)",
        "rx": 0,
        "ry": 0,
        "opacity": "0.6",
        "display": "none",
        "rotate": 60,
        "transform": "rotate(60deg)",
        "dx": "15",
        "dy": "25"
      },
      {
        "id": 4,
        "layer": "rect",
        "x": 300,
        "y": 300,
        "width": "100%",
        "height": "100%",
        "strokeWidth": 25,
        "fill": "url(#dots)",
        "rx": 0,
        "ry": 0,
        "opacity": "0.6",
        "display": "none",
        "rotate": 60,
        "transform": "rotate(60deg)",
        "dx": "15",
        "dy": "25"
      },
      {
        "id": 5,
        "layer": "text",
        "x": "100",
        "y": "200",
        "fill": "white",
        "fontFamily": "Gloss_And_Bloom",
        "fontSize": "350%",
        "fontWeight": "bold",
        "fontStyle": "normal",
        "lineHeight": 1.5,
        "letterSpacing": 0,
        "textTransform": "uppercase",
        "textShadow": "none",
        "dominantBaseline": "middle",
        "content": "Nangoli Eric Nafuna",
        "opacity": 1,
        "filter": "none",
        "display": "",
        "className": "ico",
        "rotate": 90,
        "transform": "rotateX(20deg) skewY(4deg) translate3d(0, 0, 200px)",
        "dx": "10",
        "dy": "20"
      },
      {
        "id": 6,
        "layer": "image",
        "x": 10,
        "y": 10,
        "width": "100%",
        "height": "100%",
        "aspectRatio": 5,
        "objectFit": "contain",
        "imageUrl": "none",
        "display": "none",
        "rotate": 0,
        "transform": "rotate(0deg)",
        "dx": "0",
        "dy": "0"
      }
    ]
  }
]
